project_id = "rgcqhfswkcgjtiwaalrd"

[functions.confirm-blessing]
verify_jwt = false

[functions.process-board-task]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.sms-status-webhook]
verify_jwt = false
